[package]
name = "base3DR"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.0"
dear-imgui-glow = "0.15.1"
dear-imgui-rs = "0.15.1"
dear-imgui-winit = "0.15.1"
glam = "0.33.2"
glow = "0.17.0"
gltf = "1.4.1"
glutin = "0.32.3"
glutin-winit = "0.5.0"
image = "0.25.10"
rand = "0.10.2"
raw-window-handle = "0.6.2"
rfd = "0.17.2"
thiserror = "2.0.19"
tobj = "4.0.4"
winit = "0.30.13"
